server:
  port: 9001
spring:
  datasource:
    dynamic:
      druid: #以下是全局默认值，可以全局更改
        initial-size: 0
        max-active: 8
        min-idle: 2
        max-wait: -1
        min-evictable-idle-time-millis: 30000
        max-evictable-idle-time-millis: 30000
        time-between-eviction-runs-millis: 0
        validation-query: select 1 from dual
        validation-query-timeout: -1
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        pool-prepared-statements: true
        max-open-prepared-statements: 100
        filters: stat,wall
        share-prepared-statements: true
      primary: oracle
      datasource:
        master:
          username: root
          password: zzsdzfp@123456
          url: jdbc:mysql://192.168.100.185:3306/af40?useUnicode=true&amp;characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
          driver-class-name: com.mysql.jdbc.Driver
        mysql_af41:
          username: root
          password: zzsdzfp@123456
          url: jdbc:mysql://192.168.100.185:3306/af41?useUnicode=true&amp;characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
          driver-class-name: com.mysql.jdbc.Driver
        oracle:
          username: CRM
          password: CRM
          url: jdbc:oracle:thin:@192.168.100.45:1521:ORCL
          driver-class-name: oracle.jdbc.driver.OracleDriver


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.aisino.invoice.vo

